from __future__ import print_function
import time
import boto3
import requests

def transcribeAudio(uri):
	transcribe = boto3.client('transcribe')

	suffix = str(int(round(time.time() * 1000)))
	job_name = "TranscribeJob_" + suffix
	job_uri = "https://test-transcribe-pennapps.s3.us-east-2.amazonaws.com/paragraph.m4a"
	# job_uri = "https://rekognition-video-console-demo-cmh-216642912391-s0rhpdsqexn37c.s3.us-east-2.amazonaws.com/y2mate.com_short_people_are_angrier_more_violent_than_tall_people_cdc_says_RDSwsM0oCAw_360p.mp4"

	transcribe.start_transcription_job(
	    TranscriptionJobName=job_name,
	    Media={'MediaFileUri': job_uri},
	    MediaFormat='mp4',
	    LanguageCode='en-US'
	)

	start_time = time.time()
	while True:
		print("wait...")
		status = transcribe.get_transcription_job(TranscriptionJobName=job_name)
		if status['TranscriptionJob']['TranscriptionJobStatus'] in ['COMPLETED', 'FAILED']:
			break
		time.sleep(5)
	print("--- %s seconds ---" % (time.time() - start_time))

	# A presigned URL is generated by an AWS user who has access to the object. 

	# The presigned URL remains valid for a limited period of time after URL 
	# is generated.
	response_uri = status['TranscriptionJob']['Transcript']['TranscriptFileUri']

	if response_uri is not None:
		response = requests.get(response_uri)
		print(response.text)
	text = response.json()['results']['transcripts']
	final_text = text[0]['transcript']

	return final_text