from __future__ import print_function
import time
import boto3
import requests

def transcribeAudio(uri):
	transcribe = boto3.client('transcribe')

	suffix = str(int(round(time.time() * 1000)))
	job_name = "TranscribeJob_" + suffix

	media = uri.split(".")[-1]

	transcribe.start_transcription_job(
	    TranscriptionJobName=job_name,
	    Media={'MediaFileUri': uri},
	    MediaFormat=media,
	    LanguageCode='en-US'
	)

	while True:
		status = transcribe.get_transcription_job(TranscriptionJobName=job_name)
		if status['TranscriptionJob']['TranscriptionJobStatus'] in ['COMPLETED', 'FAILED']:
			break
		time.sleep(5)

	# A presigned URL is generated by an AWS user who has access to the object. 

	# The presigned URL remains valid for a limited period of time after URL 
	# is generated.
	response_uri = status['TranscriptionJob']['Transcript']['TranscriptFileUri']

	if response_uri is not None:
		response = requests.get(response_uri)

	text = response.json()['results']['transcripts']
	final_text = text[0]['transcript']

	return final_text